# Generated by Django 5.0.14 on 2026-02-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='color',
            field=models.CharField(blank=True, default='blue', max_length=30),
        ),
        migrations.AddField(
            model_name='role',
            name='icon',
            field=models.CharField(blank=True, default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. {"leads": ["view","create","update"], "users": ["view"]}'),
        ),
    ]
