# Generated by Django 5.0.14 on 2025-12-03 06:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributionSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attribution_sources',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('planned', 'Planned'), ('active', 'Active'), ('ended', 'Ended')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lead_uuid', models.UUIDField(default=uuid.uuid4)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_doc_id', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('rejected', 'Rejected'), ('converted', 'Converted'), ('expired', 'Expired')], default='new', max_length=30)),
                ('potential_product', models.CharField(blank=True, max_length=150, null=True)),
                ('captured_at', models.DateTimeField()),
                ('server_received_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deduplicated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'leads',
            },
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(blank=True, choices=[('call', 'Call'), ('visit', 'Visit'), ('reminder', 'Reminder'), ('verification', 'Verification')], max_length=80, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lead_interactions',
            },
        ),
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('old_status', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lead_status_history',
            },
        ),
    ]
