# Generated by Django 5.0.14 on 2026-02-10 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='tenancy.agent'),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='tenancy.customer'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='leadapplication',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadapplication',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_applications', to='tenancy.product'),
        ),
        migrations.AddField(
            model_name='leadapplication',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_applications', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='lead',
            name='primary_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.leadapplication'),
        ),
        migrations.AddField(
            model_name='leadpipeline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='tenancy.product'),
        ),
        migrations.AddField(
            model_name='leadpipeline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_pipelines', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='leadapplication',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='leads.leadpipeline'),
        ),
        migrations.AddField(
            model_name='leadstage',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='leads.leadpipeline'),
        ),
        migrations.AddField(
            model_name='leadstage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_stages', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='leadapplication',
            name='current_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_applications', to='leads.leadstage'),
        ),
        migrations.AddField(
            model_name='leadstagehistory',
            name='from_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from', to='leads.leadstage'),
        ),
        migrations.AddField(
            model_name='leadstagehistory',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadstagehistory',
            name='lead_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='leads.leadapplication'),
        ),
        migrations.AddField(
            model_name='leadstagehistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_stage_history', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='leadstagehistory',
            name='to_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_to', to='leads.leadstage'),
        ),
        migrations.AddField(
            model_name='leadapplication',
            name='last_stage_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.leadstagehistory'),
        ),
        migrations.AlterUniqueTogether(
            name='leadpipeline',
            unique_together={('tenant', 'product', 'name')},
        ),
        migrations.AddIndex(
            model_name='leadstage',
            index=models.Index(fields=['tenant', 'pipeline', 'name'], name='lead_stages_tenant__d66d68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leadstage',
            unique_together={('tenant', 'pipeline', 'stage_order')},
        ),
        migrations.AddIndex(
            model_name='leadstagehistory',
            index=models.Index(fields=['tenant', 'lead_application', 'changed_at'], name='lead_stage__tenant__021e18_idx'),
        ),
    ]
