# Generated by Django 5.0.14 on 2026-02-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPIAgentDaily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kpi_date', models.DateField()),
                ('leads_captured', models.IntegerField(default=0)),
                ('leads_converted', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('revenue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('avg_time_to_convert', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'kpi_agent_daily',
            },
        ),
    ]
