# Generated by Django 5.0.14 on 2025-12-03 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiagentdaily',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_kpis', to='tenancy.agent'),
        ),
        migrations.AddField(
            model_name='kpiagentdaily',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_kpis', to='tenancy.outlet'),
        ),
        migrations.AddField(
            model_name='kpiagentdaily',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_kpis', to='tenancy.region'),
        ),
        migrations.AddField(
            model_name='kpiagentdaily',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_kpis', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='kpioutletdaily',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_kpis', to='tenancy.outlet'),
        ),
        migrations.AddField(
            model_name='kpioutletdaily',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_kpis', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='kpiagentdaily',
            index=models.Index(fields=['tenant', 'kpi_date'], name='kpi_agent_d_tenant__076759_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiagentdaily',
            index=models.Index(fields=['agent', 'kpi_date'], name='kpi_agent_d_agent_i_781f66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kpiagentdaily',
            unique_together={('tenant', 'agent', 'kpi_date')},
        ),
        migrations.AddIndex(
            model_name='kpioutletdaily',
            index=models.Index(fields=['tenant', 'kpi_date'], name='kpi_outlet__tenant__07ff6d_idx'),
        ),
        migrations.AddIndex(
            model_name='kpioutletdaily',
            index=models.Index(fields=['outlet', 'kpi_date'], name='kpi_outlet__outlet__872e66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kpioutletdaily',
            unique_together={('tenant', 'outlet', 'kpi_date')},
        ),
    ]
