# Generated by Django 5.0.14 on 2026-02-10 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiagentdaily',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_kpis', to='tenancy.agent'),
        ),
        migrations.AddField(
            model_name='kpiagentdaily',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_kpis', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='kpiagentdaily',
            index=models.Index(fields=['tenant', 'kpi_date'], name='kpi_agent_d_tenant__076759_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiagentdaily',
            index=models.Index(fields=['agent', 'kpi_date'], name='kpi_agent_d_agent_i_781f66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kpiagentdaily',
            unique_together={('tenant', 'agent', 'kpi_date')},
        ),
    ]
