# Generated by Django 5.0.14 on 2025-12-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_sale_id', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sale_currency', models.CharField(default='UZS', max_length=10)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('converted_at', models.DateTimeField()),
                ('source_system', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'conversions',
            },
        ),
        migrations.CreateModel(
            name='ExternalImportBatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_system', models.CharField(max_length=100)),
                ('import_type', models.CharField(choices=[('sales', 'Sales'), ('costs', 'Costs'), ('agents', 'Agents')], max_length=50)),
                ('file_name', models.CharField(blank=True, max_length=300, null=True)),
                ('imported_at', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], max_length=30, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'external_import_batches',
            },
        ),
        migrations.CreateModel(
            name='ExternalSalesImport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_sale_id', models.CharField(max_length=200)),
                ('outlet_code', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_code', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'external_sales_import',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('revenue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'ledger_entries',
            },
        ),
    ]
