# Generated by Django 5.0.14 on 2025-12-03 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversions', '0002_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='externalimportbatch',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalimportbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='externalsalesimport',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='conversions.externalimportbatch'),
        ),
        migrations.AddField(
            model_name='externalsalesimport',
            name='matched_conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_records', to='conversions.conversion'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='tenancy.agent'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='conversions.conversion'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='tenancy.outlet'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='tenancy.tenant'),
        ),
    ]
