# Generated by Django 5.0.14 on 2025-12-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCalculationItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gross_bonus', models.DecimalField(decimal_places=2, max_digits=18)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bonus_calculation_items',
            },
        ),
        migrations.CreateModel(
            name='BonusCalculationRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bonus_calculation_runs',
            },
        ),
        migrations.CreateModel(
            name='BonusPayoutExport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('export_format', models.CharField(blank=True, choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('xml', 'XML')], max_length=30, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bonus_payout_exports',
            },
        ),
        migrations.CreateModel(
            name='BonusRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('per_conversion', 'Per Conversion'), ('per_lead', 'Per Lead'), ('per_target', 'Per Target'), ('tier', 'Tier')], max_length=80)),
                ('condition_expr', models.TextField(blank=True, null=True)),
                ('amount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent_of_sale', 'Percent of Sale')], max_length=30)),
                ('amount_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cap_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('priority', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'bonus_rules',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='BonusRuleSet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'bonus_rule_sets',
            },
        ),
    ]
