# Generated by Django 5.0.14 on 2026-02-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rule_dimension', models.CharField(blank=True, choices=[('LEAD_TIME', 'Lead Time'), ('SELL_TIME', 'Sell Time'), ('USER_REG_TIME', 'User Registration Time'), ('SELL_AMOUNT', 'Sell Amount'), ('POTENTIAL_PRODUCT', 'Potential Product'), ('LEAD_TO_SELL_DELTA', 'Lead to Sell Delta')], max_length=40, null=True)),
                ('operator', models.CharField(blank=True, choices=[('EQ', 'Equal'), ('NEQ', 'Not Equal'), ('GT', 'Greater Than'), ('GTE', 'Greater Than or Equal'), ('LT', 'Less Than'), ('LTE', 'Less Than or Equal'), ('BETWEEN', 'Between'), ('IN', 'In'), ('NOT_IN', 'Not In')], max_length=30, null=True)),
                ('ts_from', models.DateTimeField(blank=True, null=True)),
                ('ts_to', models.DateTimeField(blank=True, null=True)),
                ('num_from', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('num_to', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('interval_from', models.DurationField(blank=True, null=True)),
                ('interval_to', models.DurationField(blank=True, null=True)),
                ('text_values', models.TextField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('amount_type', models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percent_of_sale', 'Percent of Sale')], max_length=30, null=True)),
                ('amount_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cap_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'bonus_rules',
            },
        ),
        migrations.CreateModel(
            name='CommissionPolicy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('mode', models.CharField(max_length=40)),
                ('window_interval', models.DurationField(blank=True, null=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'commission_policies',
            },
        ),
    ]
