# Generated by Django 5.0.14 on 2026-02-10 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bonuses', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_rules', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='commissionpolicy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_policies', to='tenancy.tenant'),
        ),
    ]
