# Generated by Django 5.0.14 on 2025-12-03 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bonuses', '0001_initial'),
        ('conversions', '0001_initial'),
        ('leads', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuscalculationitem',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_items', to='tenancy.agent'),
        ),
        migrations.AddField(
            model_name='bonuscalculationitem',
            name='conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_items', to='conversions.conversion'),
        ),
        migrations.AddField(
            model_name='bonuscalculationitem',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_items', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='bonuscalculationitem',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_items', to='tenancy.outlet'),
        ),
        migrations.AddField(
            model_name='bonuscalculationrun',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_calc_runs', to='tenancy.tenant'),
        ),
    ]
