# Generated by Django 5.0.14 on 2026-03-18 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0002_initial'),
        ('conversions', '0002_initial'),
        ('tenancy', '0004_seed_subscription_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusLedger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('calculation_detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_ledger_entries', to='tenancy.agent')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='bonuses.bonusrule')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_ledger', to='conversions.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_ledger_entries', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'bonus_ledger',
            },
        ),
    ]
