# Generated by Django 5.0.14 on 2025-12-03 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bonuses', '0002_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuscalculationrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_bonus_calcs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonuscalculationitem',
            name='calc_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_items', to='bonuses.bonuscalculationrun'),
        ),
        migrations.AddField(
            model_name='bonuspayoutexport',
            name='calc_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='bonuses.bonuscalculationrun'),
        ),
        migrations.AddField(
            model_name='bonuspayoutexport',
            name='exported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonuspayoutexport',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_exports', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='bonuscalculationitem',
            name='applied_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_items', to='bonuses.bonusrule'),
        ),
        migrations.AddField(
            model_name='bonusruleset',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_rule_sets', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='bonusrule',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='bonuses.bonusruleset'),
        ),
    ]
