# Generated by Django 5.0.14 on 2026-04-05 13:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_initial'),
        ('tenancy', '0004_seed_subscription_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadConversation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_person', 'In Person'), ('phone', 'Phone'), ('email', 'Email'), ('online_chat', 'Online Chat')], max_length=20)),
                ('audio_file', models.FileField(blank=True, help_text='Voice recording for in_person/phone channels', null=True, upload_to='conversations/audio/%Y/%m/')),
                ('raw_transcript', models.TextField(blank=True, help_text='Chat transcript (uploaded) or transcribed from audio', null=True)),
                ('transcription_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('rating', models.IntegerField(blank=True, help_text='AI-assigned agent performance rating (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('conversation_topic', models.CharField(blank=True, help_text='AI-extracted main topic of the conversation', max_length=255, null=True)),
                ('short_description', models.TextField(blank=True, help_text='AI-generated brief summary of the conversation', null=True)),
                ('conversation_outcome', models.TextField(blank=True, help_text='AI-generated description of the conversation result', null=True)),
                ('customer_sentiment', models.CharField(blank=True, choices=[('very_negative', 'Very Negative'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('positive', 'Positive'), ('very_positive', 'Very Positive')], max_length=20, null=True)),
                ('ai_raw_response', models.JSONField(blank=True, help_text='Full AI response for debugging/auditing', null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='tenancy.agent')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='leads.lead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_conversations', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'lead_conversations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'agent'], name='lead_conver_tenant__ec44f3_idx'), models.Index(fields=['tenant', 'customer_sentiment'], name='lead_conver_tenant__a3be47_idx'), models.Index(fields=['tenant', 'rating'], name='lead_conver_tenant__9f504e_idx')],
            },
        ),
    ]
